name = "STBImage"
uuid = "7905c688-fe39-11e9-31c9-6bac3ecc6ce7"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CSyntax = ">= 0.2.0"
BinaryProvider = ">= 0.3.0"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
