name = "STBImage"
uuid = "7905c688-fe39-11e9-31c9-6bac3ecc6ce7"
authors = ["Yupei Qi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
